### ISSUE TITLE
redis default url

### ISSUE THREAD

**Issue by x8-999-github** [aliasaria/scrumblr#110]
Hi,

I am getting the following redis related error error 

```
Server running at http://127.0.0.1:8080/
Opening redis connection to 127.0.0.1:6379
/home/etherpad/scrumblr/node_modules/redis/lib/createClient.js:61
            throw new RangeError('The redis url must begin with slashes "//" or contain slashes after the redis protocol');
            ^

RangeError: The redis url must begin with slashes "//" or contain slashes after the redis protocol
    at createClient (/home/etherpad/scrumblr/node_modules/redis/lib/createClient.js:61:19)
    at Object.exports.createClient (/home/etherpad/scrumblr/node_modules/redis/index.js:1089:41)
    at db (/home/etherpad/scrumblr/lib/data/redis.js:20:22)
    at Object.<anonymous> (/home/etherpad/scrumblr/server.js:499:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

```

```
apt-cache policy redis-server
redis-server:
  Installed: 2:3.2.1-1
  Candidate: 2:3.2.1-1
  Version table:
 *** 2:3.2.1-1 500
        500 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
        100 /var/lib/dpkg/status
```

```
 node -v
v7.10.0
```

That I was able to "fix" by changing the config url to start with redis:// e.g.

```
diff --git a/config.js b/config.js
index d236029..407eaea 100644
--- a/config.js
+++ b/config.js
@@ -23,6 +23,6 @@ exports.googleanalytics = {
 exports.database = {
        type: 'redis',
        prefix: '#scrumblr#',
-       redis: argv.redis || '127.0.0.1:6379'
+       redis: argv.redis || 'redis://127.0.0.1:6379'
 };
```

**Comment by nickeeromo** [comment]
I can confirm this is an issue, easily fixed.  Did you create a pull request for the fix?

**Comment by rsrini7** [comment]
Please open redis/lib/createClient.js under node_modules.

} else if (typeof port_arg === 'string' || port_arg && port_arg.url) {

        options = utils.clone(port_arg.url ? port_arg : host_arg || options);
        var url = port_arg.url || port_arg;
        url = "redis://"+url; // this append works

**Comment by x8-999-github** [comment]
Hence the idea is to modify the client code and not modify the config?

**Comment by rsrini7** [comment]
Just noticed. config.js. Thanks. updated and works great.

**Comment by moenka** [comment]
The error is still in the code. The correct fix would be the one from @x8-999-github. The solution from @rsrini7 is modifying the redis node module which should be fixed within the redis repository. @aliasaria  Can you please implement the fix for the config?

**Comment by zcool99** [comment]
Amazing solution, you need to update the config.js with the new line :)

**Comment by x8-999-github** [comment]
Thanks for the fix!
